### ISSUE TITLE
Crash when input item isn't a BlockItem

### ISSUE THREAD

**Issue by EvanHsieh0415** [iglee42/create-more-recipes#1]
```json
{
  "type": "cmr:custom_fan",
  "ingredients": [
    "ender_pearl",
    "ender_pearl"
  ],
  "results": ["ender_eye"]
}
```

```java
[09:21:02] [Render thread/ERROR] [minecraft/Minecraft]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:978) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.5.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?] {}
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?] {}
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?] {}
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?] {re:mixin}
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?] {re:mixin}
	at fr.iglee42.cmr.jei.FanCustomCategory.draw(FanCustomCategory.java:55) ~[cmr-1.0.1.jar%23168!/:1.0.1] {re:classloading}
	at fr.iglee42.cmr.jei.FanCustomCategory.draw(FanCustomCategory.java:22) ~[cmr-1.0.1.jar%23168!/:1.0.1] {re:classloading}
	at mezz.jei.library.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:193) ~[jei-1.20.1-forge-15.19.0.88.jar%23171!/:15.19.0.88] {re:classloading}
	at mezz.jei.gui.recipes.RecipeGuiLayouts.draw(RecipeGuiLayouts.java:189) ~[jei-1.20.1-forge-15.19.0.88.jar%23171!/:15.19.0.88] {re:classloading}
	at mezz.jei.gui.recipes.RecipesGui.m_88315_(RecipesGui.java:265) ~[jei-1.20.1-forge-15.19.0.88.jar%23171!/:15.19.0.88] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinScreen,pl:mixin:APP:kubejs-common.mixins.json:ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.3.5-universal.jar%23183!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.3.5-universal.jar%23183!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	... 26 more
```

**Comment by iglee42** [comment]
It seems logic for me, I don't see the problem, you won't fan an item with another item

**Comment by EvanHsieh0415** [comment]
> It seems logic for me, I don't see the problem, you won't fan an item with another item

I'd like to be able to export error logs instead of crashes, which would make writing recipes a bit more cumbersome!

**Comment by iglee42** [comment]
Your recipe won't work did you follow the example on the curseforge page ?

```JS
{
  "type": "cmr:custom_fan",
  "ingredients": [
    {
      "tag": "forge:cobblestone" //Item to throw
    },
    {
      "item": "minecraft:oak_fence" //Block behind the fan (Optional if fluid present)
    },
    {
      "amount": 1000,
      "fluid": "create:honey", // Fluid (Optional if block present)
      "nbt": {}
    }
  ],
  "results": [
    {
      "item": "minecraft:diamond" //Result Item
    }
  ]
}

**Comment by EvanHsieh0415** [comment]
> Your recipe won't work did you follow the example on the curseforge page ?
> 
> ```js
> {
>   "type": "cmr:custom_fan",
>   "ingredients": [
>     {
>       "tag": "forge:cobblestone" //Item to throw
>     },
>     {
>       "item": "minecraft:oak_fence" //Block behind the fan (Optional if fluid present)
>     },
>     {
>       "amount": 1000,
>       "fluid": "create:honey", // Fluid (Optional if block present)
>       "nbt": {}
>     }
>   ],
>   "results": [
>     {
>       "item": "minecraft:diamond" //Result Item
>     }
>   ]
> }
> ```

I originally made the recipe in kjs, I forgot about it when I converted it to a json recipe, so it should be
```json
{
  "type": "cmr:custom_fan",
  "ingredients": [
    { "item": "ender_pearl" },
    { "item": "ender_pearl" }
  ],
  "results": [{ "item": "ender_eye" }]
}
```

**Comment by iglee42** [comment]
Should be fixed with the last update
